apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whatsapp-api
  name: whatsapp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whatsapp-api
    spec:
      containers:
      - image: hiteshdutt/whatsapp-api
        env:
        - name: DATABASE_URL
          value: "postgres_connection_string"
        - name: PORT
          value: "3000"
        - name: API_KEY
          value: "api_key_for_verfication_on_api"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FILE
          value: "/app/logs/whatsapplogs/app.log"
        - name: CONSOLE_LOG_FILE
          value: "/app/logs/whatsapplogs/app.console.log"
        command: [ "/bin/sh", "-c" ]
        args: [ "node /app/dist/index.js" ]
        imagePullPolicy: IfNotPresent
        name: whatsapp-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
          - mountPath: /app/logs/whatsapplogs/
            name: volume
            readOnly: false
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: whatsapp-file-pvc