name: Docker Build and Push

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build'
                required: true
                default: 'development'
                type: string
    push:
        branches:
        - development
        - main

jobs:
    DockerBuildPush:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.5
              with:
                  fetch-depth: 0
            - name: Login to DockerHub
              uses: docker/login-action@v3.1.0
              with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build
              uses: docker/build-push-action@v5.3.0
              with: 
                    file: ./Dockerfile.tbr
                    tags: hiteshdutt/whatsapp-api:${{ github.run_id }}
                    push: true
